# Generated by Django 4.0.3 on 2022-04-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0010_delete_charactergoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('characer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='games.character')),
            ],
        ),
    ]
