# Generated by Django 4.0.3 on 2022-04-05 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('items', models.TextField()),
                ('playersclass', models.CharField(max_length=50)),
                ('skills', models.TextField()),
                ('spells', models.TextField()),
                ('goals', models.TextField()),
                ('goalscomplete', models.BooleanField(default=b'I00\n')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('ac', models.IntegerField()),
                ('race', models.CharField(choices=[('Elf', 'Elf'), ('Dwarf', 'Dwarf')], default='Elf', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField(verbose_name='Discord link image')),
                ('members', models.ManyToManyField(related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('items', models.TextField()),
                ('playersclass', models.CharField(max_length=50)),
                ('skills', models.TextField()),
                ('spells', models.TextField()),
                ('goals', models.TextField()),
                ('goalscomplete', models.BooleanField(default=b'I00\n')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='games.character')),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.stats')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='games.game'),
        ),
        migrations.AddField(
            model_name='character',
            name='stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.stats'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
    ]
