# Generated by Django 4.0.3 on 2022-04-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
