# Generated by Django 4.0.3 on 2022-04-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_delete_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='items',
        ),
        migrations.RemoveField(
            model_name='character',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spells',
        ),
        migrations.RemoveField(
            model_name='character',
            name='stats',
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('Elf', 'Elf'), ('Dwarf', 'Dwarf')], default='Elf', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='goalscomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
