# Generated by Django 4.0.3 on 2022-04-06 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_charactergoal_list_charactergoal_characer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactergoal',
            old_name='goal',
            new_name='name',
        ),
    ]
