# Generated by Django 4.0.3 on 2022-04-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_rename_goal_charactergoal_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterGoal',
        ),
    ]
