# Generated by Django 4.0.3 on 2022-04-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_charactergoal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterGoal',
        ),
    ]
