# Generated by Django 4.0.3 on 2022-04-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_game_user_alter_character_playersclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
    ]
