# Generated by Django 4.0.3 on 2022-04-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_game_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
    ]
